#!/bin/sh

#initDir=$(pwd)
#confDirs=$(find dot-config/ -type d | tail -n +2)
#for sourceDir in $confDirs; do
    #targetDir=$(echo $sourceDir | sed 's/^dot-config/~\/\.config/g')
    #[ -d "$targetDir" ] && mkdir -p "$targetDir"
    #cd "${sourceDir%/*}"
    #stow --verbose --dotfiles --target="$targetDir" "${sourceDir##*/}"
    #cd "$initDir"
#done

stow --verbose --dotfiles --target=$HOME/.config dot-config
stow --verbose --dotfiles --target=$HOME/.local/share local-share
stow --verbose --dotfiles --target=$HOME/.local/bin local-bin
#cd dot-config/
#stow --verbose --dotfiles --target=$HOME/.config/vim vim
