#!/bin/sh

# script to display the battery state in dwmblocks

#acpi -b | grep -q "Battery 0" || { printf ""; exit; }
#
#BATTERYSTATE=$( acpi -b | awk '{ split($5,a,":"); print substr($3,0,2), $4, "["a[1]":"a[2]"]" }' | tr -d ',DiFu' )
#if [[ $BATTERYSTATE =~ "Ch" ]]; then
    #icon="⚡"
#else
    #icon="🔋"
#fi
#batterypercent=$(echo "$BATTERYSTATE" | tr -d 'Ch' | sed 's/cargng:/?/')

percent="$(cat /sys/class/power_supply/BAT*/capacity)"

if grep -q 'Discharging' /sys/class/power_supply/BAT*/status; then
    if [ "$percent" -gt 89 ]; then
        icon=" "
    elif [ "$percent" -gt 74 ]; then
        icon=" "
    elif [ "$percent" -gt 49 ]; then
        icon=" "
    elif [ "$percent" -gt 24 ]; then
        icon=" "
    else
        icon=" "
    fi
elif grep -q 'Charging' /sys/class/power_supply/BAT*/status; then
    icon=" "
    if [ "$percent" -eq 100 ]; then
        percent="99"
    fi
elif grep -q 'Full' /sys/class/power_supply/BAT*/status; then
    icon=" "
else
    icon=" "
fi

printf "%s %s\\n" "$icon" "$percent"
