#!/bin/sh

# script to save the brightness state so it is the same after a restart

device=$(brightnessctl -l | grep "class 'backlight'" | head -n 1 | awk '{print $2}' | tr -d "'")
[ -z "$device" ] && { printf ""; exit; }

printf "%s\\n" "$(brightnessctl -d "${device}" | grep Current | awk -F '[)(]' '{print $2}' | tr -d "%")" > ~/.config/norisa/brightness-state
