#!/bin/sh

# script to display the brightness state in dwmblocks

device=$(brightnessctl -l | grep "class 'backlight'" | tail -n +3 | awk '{print $2}' | tr -d "'")
if brightnessctl -l | grep "class 'backlight'" | grep -q "^Device 'acpi_video0'"; then
    device="acpi_video0"
fi
[ -z "$device" ] && { printf ""; exit; }

printf "🔆 %s\\n" "$(brightnessctl -d "${device}" | grep Current | awk -F '[)(]' '{print $2}')"
