#!/bin/sh

# script to save the brightness state so it is the same after a restart

device=$(brightnessctl -l | grep "class 'backlight'" | tail -n +2 | awk '{print $2}' | tr -d "'")
if brightnessctl -l | grep "class 'backlight'" | grep -q "^Device 'intel_backlight'\|^Device 'acpi_video"; then
    device="$(brightnessctl -l | grep "class 'backlight'" | awk '{print $2}' | tr -d "'")"
fi
[ -z "$device" ] && { printf ""; exit; }


mkdir -p "$HOME/.config/norisa"
printf "%s\\n" "$(brightnessctl -d "${device}" | grep Current | awk -F '[)(]' '{print $2}' | tr -d "%")" > ~/.config/norisa/brightness-state
