#!/bin/sh

# script to change the java environment using fuzzel from the commandline

env="$(archlinux-java status | grep java | fuzzel -d -l 30)"

# exit if none selected
[ -z "$env" ] && exit

# set new environment
sudo archlinux-java set "$env"
