#!/bin/sh

# The famous "get a menu of emojis to copy" script. (copied from Luke Smith)

# get user selection via fuzzel from emoji file.
chosen=$(cut -d ';' -f1 ~/.local/share/norisa/emoji | fuzzel -d -l 30 | sed "s/ .*//")

# exit if none chosen.
[ -z "$chosen" ] && exit

echo "$chosen" | tr -d '\n' | wl-copy
