#!/bin/sh

# script to get a selection of greek letters using fuzzel

selected=$(fuzzel -d -l 25 < ~/.local/share/norisa/greek-letters)

# exit if none selected
[ -z "$selected" ] && exit

# copies the selected letter in the desired format
case "${1##-}" in
	vim) echo "\\${selected##* }" | tr -d '\n' | wl-copy ;;
	*) echo "${selected%% *}" | tr -d '\n' | wl-copy ;;
esac
