#!/usr/bin/env python3

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from sys import argv

options = webdriver.ChromeOptions()
options.add_extension(argv[1])
options.add_extension(argv[2])
try:
    driver = webdriver.Chrome(options=options)
except:
    print("Error: Could not connect to webdriver")
    exit(1)

driver.get(argv[3])
with open(argv[4], "w") as f:
    f.write(driver.page_source)
f.close()
driver.quit()
