#!/bin/sh

 git -c color.diff.new='bold reverse green' \
    -c color.diff.old='bold reverse red' diff --no-index -U0 --no-color \
    --word-diff=color --word-diff-regex=. \
    $1 $2 | tail -n +3 |
    grep -v '\-\-\-\|+++'
