#!/bin/sh

makepkg -fC
if sendreportmail | grep -q "BUILD SUCCESS"; then
    git push
    if echo "$1$2" | grep -q "c"; then
        cr
    fi
    if echo "$1$2" | grep -q "x"; then
        xup *.pkg.tar.zst
    fi
fi
sudo systemctl suspend
