#!/bin/bash

for (( i=0; i < 3; i++ )); do
    sudo GNUPGHOME=/home/builder/.local/share/gnupg ccm64 s && break
done
rm *-debug*.pkg.tar.zst
if sendreportmail | grep -q "BUILD SUCCESS"; then
    git push
    if echo "$1$2" | grep -q "c"; then
        cr
    fi
    if echo "$1$2" | grep -q "x"; then
        xup *.pkg.tar.zst
    fi
fi
sudo systemctl suspend
