#!/bin/sh

# script to make a screenshot from the desired selection

[ ! -d "$HOME/dox/screenshots" ] && mkdir -p "$HOME/dox/screenshots"

if [ -f "$HOME/dox/screenshots/Screenshot_$(date +"%Y%m%d-%H%M%S")_dwm.jpg" ]; then
    import "dox/screenshots/Screenshot_$(date +"%Y%m%d-%H%M%S")_dwm_$(date +"%N").jpg"
else
    import "dox/screenshots/Screenshot_$(date +"%Y%m%d-%H%M%S")_dwm.jpg"
fi
