#!/bin/sh

# script to make a screenshot of the full screen area

[ ! -d "$HOME/pix/screenshots" ] && mkdir-p "$HOME/pix/screenshots"

import -windows root "pix/screenshots/$(date +"%F--%H-%M-%S--%N").jpg"
