#!/bin/sh

# TeX template for a beamer presentation

# exit if no argument given
[ -z "$*" ] && echo "Error: Usage: nb [filename]" && exit

cp ~/.config/setup/templates/latex/beamer.tex .
mv beamer.tex "${1%.*}.tex"
vim -c :1  "${1%.*}.tex"
