#!/bin/sh

# TeX template for use in school

# exit if no argument given
[ -z "$*" ] && echo "Error: Usage: sl [filename]" && exit

cp ~/.config/setup/templates/latex/school-template.tex .
mv school-template.tex "${1%.*}.tex"
nvim -c :72  "${1%.*}.tex"
