-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives
---@module 'hl'
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})

local mainMod = "SUPER"

--##################
--## MY PROGRAMS ###
--##################
-- See https://wiki.hypr.land/Configuring/Keywords/
-- source=~/.config/hypr/keybind.conf
-- Set programs that you use
local terminal = "kitty"
local fileManager = "nautilus"
local menu = "fuzzel"
local browser = "chromium"

--################
--## AUTOSTART ###
--################
-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:

-- exec-once = $terminal
-- exec-once = nm-applet &
-- exec-once = waybar & hyprpaper & firefox
--############################
--## ENVIRONMENT VARIABLES ###
--############################
hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_SIZE", 24)

--##################
--## PERMISSIONS ###
--##################
hl.config({
    ecosystem = {
        enforce_permissions = true,
    },
})

hl.permission({ binary = "/usr/bin/grim", type = "screencopy", mode = "allow" })
hl.permission({ binary = "/usr/bin/hyprpicker", type = "screencopy", mode = "allow" })
hl.permission({ binary = "/usr/bin/hyprlock", type = "screencopy", mode = "allow" })
hl.permission({ binary = "/usr/lib/xdg-desktop-portal-hyprland", type = "screencopy", mode = "allow" })

--####################
--## LOOK AND FEEL ###
--####################
-- Refer to https://wiki.hypr.land/Configuring/Variables/
-- https://wiki.hypr.land/Configuring/Variables/#general
hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 15,
        border_size = 2,
        -- https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,
        allow_tearing = false,
        layout = "master",
        col = {
            active_border = "rgba(33ccffee)",
            inactive_border = "rgba(595959aa)",
        },
    },
})

hl.config({
    cursor = {
        inactive_timeout = 4,
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#decoration
hl.config({
    decoration = {
        rounding = 10,
        rounding_power = 2,
        -- Change transparency of focused and unfocused windows
        active_opacity = 0.95,
        inactive_opacity = 0.95,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        -- https://wiki.hypr.land/Configuring/Variables/#blur
        blur = {
            enabled = true,
            size = 3,
            passes = 1,
            vibrancy = 0.1696,
        },
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#animations
hl.config({
    animations = {
        enabled = true,
        -- Default curves, see https://wiki.hypr.land/Configuring/Animations/#curves
        --        NAME,           X0,   Y0,   X1,   Y1
        -- Default animations, see https://wiki.hypr.land/Configuring/Animations/
        --           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
    },
})

-- Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- workspace = w[tv1], gapsout:0, gapsin:0
-- workspace = f[1], gapsout:0, gapsin:0
-- windowrule {
--     name = no-gaps-wtv1
--     match:float = false
--     match:workspace = w[tv1]
--
--     border_size = 0
--     rounding = 0
-- }
--
-- windowrule {
--     name = no-gaps-f1
--     match:float = false
--     match:workspace = f[1]
--
--     border_size = 0
--     rounding = 0
-- }
-- See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true,
        -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#misc
hl.config({
    misc = {
        force_default_wallpaper = -1,
        -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = false,
        -- If true disables the random hyprland logo / anime girl background. :(
    },
})

--############
--## INPUT ###
--############
-- https://wiki.hypr.land/Configuring/Variables/#input
hl.config({
    input = {
        kb_layout = "ch",
        kb_options = "caps:swapescape,altwin:swap_lalt_lwin",
        follow_mouse = 1,
        sensitivity = 0,
        -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = true,
            disable_while_typing = true,
            clickfinger_behavior = true,
        },
    },
})

-- See https://wiki.hypr.land/Configuring/Gestures
hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

-- ca 2015 Macbook Keyboard
hl.device({
    name = "apple-inc.-apple-internal-keyboard-/-trackpad",
    kb_options = "caps:swapescape,lv3:rwin_switch",
})
hl.bind("SUPER + ALT_L", hl.dsp.exec_cmd("fuzzel"), { release = true, device = "apple-inc.-apple-internal-keyboard-/-trackpad" })

-- M1 Keyboard
hl.device({
    name = "apple-spi-keyboard",
    kb_options = "caps:swapescape,lv3:rwin_switch",
})
hl.bind("SUPER + ALT_L", hl.dsp.exec_cmd("fuzzel"), { release = true, device = "apple-spi-keyboard" })

--##################
--## KEYBINDINGS ###
--##################
-- See https://wiki.hypr.land/Configuring/Keywords/
hl.bind(mainMod .. " + " .. "SUPER_L", hl.dsp.exec_cmd("fuzzel"), { release = true })

-- Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more
hl.bind(mainMod .. " + " .. "N", hl.dsp.exec_cmd("~/.local/bin/fuzzel-vpn"))
hl.bind(mainMod .. " + " .. "Return", hl.dsp.exec_cmd("kitty"))
hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Q", hl.dsp.exec_cmd("killall Hyprland"))
hl.bind(mainMod .. " + " .. "M", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit"))
hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("nautilus --new-window"))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "F", hl.dsp.window.float())
hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())

-- dwindle
hl.bind(mainMod .. " + " .. "V", hl.dsp.exec_cmd("chromium"))

-- bind = $mainMod, J, layoutmsg, togglesplit # dwindle
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "T", hl.dsp.exec_cmd("~/.config/hypr/scripts/toggle-theme.sh"))

-- Screenshots
hl.bind("Print", hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh area"))
hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "Print", hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh monitor"))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Print", hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh window"))
hl.bind("XF86LaunchA", hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh area"))
hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "XF86LaunchA", hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh monitor"))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "XF86LaunchA", hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh window"))
hl.bind(mainMod .. " + " .. "ALT" .. " + " .. "Space", hl.dsp.window.float())

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

-- Swap windows
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "left", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "right", hl.dsp.window.move({ direction = "r" }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "up", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "down", hl.dsp.window.move({ direction = "d" }))
hl.bind(mainMod .. " + " .. "H", hl.dsp.layout("mfact -0.05"), { repeating = true })
hl.bind(mainMod .. " + " .. "L", hl.dsp.layout("mfact +0.05"), { repeating = true })
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "L", hl.dsp.exec_cmd("systemctl suspend"))
hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen())

-- Master Layout Control
hl.bind(mainMod .. " + " .. "Z", hl.dsp.exec_cmd("~/.config/hypr/scripts/toggle-layout.sh"))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Return", hl.dsp.layout("swapwithmaster"))
hl.bind(mainMod .. " + " .. "J", hl.dsp.layout("cyclenext"))
hl.bind(mainMod .. " + " .. "K", hl.dsp.layout("cycleprev"))
hl.bind(mainMod .. " + " .. "I", hl.dsp.layout("addmaster"))
hl.bind(mainMod .. " + " .. "D", hl.dsp.layout("removemaster"))

-- Sets the layout to "Stacked" (Horizontal Split)
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "H", hl.dsp.layout("orientationtop"))

-- Sets the layout to "Side-by-Side" (Vertical Split)
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "V", hl.dsp.layout("orientationleft"))

-- Switch workspaces with mainMod + [0-9]
hl.bind(mainMod .. " + " .. "Tab", hl.dsp.focus({ workspace = "previous" }))
hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + " .. "S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Resize submap
hl.bind(mainMod .. " + " .. "R", hl.dsp.submap("resize"))

hl.define_submap("resize", function()
    hl.bind("right", hl.dsp.exec_cmd("hyprctl dispatch resizeactive 10 0"), { repeating = true })
    hl.bind("left", hl.dsp.exec_cmd("hyprctl dispatch resizeactive -10 0"), { repeating = true })
    hl.bind("up", hl.dsp.exec_cmd("hyprctl dispatch resizeactive 0 -10"), { repeating = true })
    hl.bind("down", hl.dsp.exec_cmd("hyprctl dispatch resizeactive 0 10"), { repeating = true })
    hl.bind("escape", hl.dsp.submap("reset"))
end)

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("~/.config/hypr/scripts/display-brightness.sh 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("~/.config/hypr/scripts/display-brightness.sh 5%-"), { locked = true, repeating = true })
hl.bind(mainMod .. " + " .. "XF86MonBrightnessUp", hl.dsp.exec_cmd("~/.config/hypr/scripts/keyboard-brightness.sh 5%+"), { locked = true, repeating = true })
hl.bind(mainMod .. " + " .. "XF86MonBrightnessDown", hl.dsp.exec_cmd("~/.config/hypr/scripts/keyboard-brightness.sh 5%-"), { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

--#############################
--## WINDOWS AND WORKSPACES ###
--#############################
-- See https://wiki.hypr.land/Configuring/Window-Rules/ for more
-- See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules
hl.window_rule({
    name  = "opaque-floating",
    match = {
        float = true,
    },
    opacity = "1.0 override 1.0 override",
})

hl.window_rule({
    name  = "suppress-maximize-events",
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

-- Fix some dragging issues with XWayland
hl.window_rule({
    name  = "fix-xwayland-drags",
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
    no_focus = true,
})

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = {
        class = "hyprland-run",
    },
    move = { 20, "monitor_h-120" },
    float = true,
})

hl.window_rule({
    name  = "browser-opacity-and-workspace",
    match = {
        class = "^(" .. browser .. ")$",
    },
    opacity = "1.0 override 1.0 override",
    opaque = true,
})

hl.window_rule({
    name  = "xwayland-video-bridge",
    match = {
        class = "^(xwaylandvideobridge)$",
    },
    opacity = "0.0 override 0.0 override",
    workspace = 9,
    no_initial_focus = true,
    max_size = { 1, 1 },
    no_blur = true,
})

hl.window_rule({
    name  = "keepassxc-workspace",
    match = {
        class = "^(org.keepassxc.KeePassXC)$",
    },
    workspace = 5,
})

hl.window_rule({
    name  = "localsend-workspace",
    match = {
        class = "^(localsend)$",
    },
    workspace = 10,
})

hl.window_rule({
    name  = "logseq-workspace",
    match = {
        class = "^(Logseq)$",
    },
    workspace = 6,
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user start hyprland-session.target")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("waybar")
    hl.exec_cmd("swaync")
    hl.exec_cmd("syncthing")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("xwaylandvideobridge")
    hl.exec_cmd("wlsunset -l 47 -L 8") -- 47 N, 8 E (Switzerland coordinates)
end)
