# go fullscreen by default
fs=yes

# use hardware acceleration
hwdec=auto

# avoid av1 (no hw decode on nearly all my devices), prefer vp9, then h264, max 1600p
ytdl-format=bv*[vcodec^=vp09][height<=1600]+ba/bv*[vcodec^=avc1][height<=1600]+ba/bv*[vcodec!^=av01][height<=1600]+ba/b[height<=1600]/b

# prefer h264
#ytdl-format=137+m4a/137+bestaudio/136+m4a/mp4[height<=1080]/mp4/best[height<=1080]/best
